# Generated by Django 4.2.3 on 2023-07-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_schema',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('add', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
    ]
