# Generated by Django 4.2.3 on 2023-09-07 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0002_alter_user_schema_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_schema',
            name='log_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
