# Generated by Django 4.2.3 on 2023-09-07 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0004_user_schema_new_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_schema',
            name='log_time',
        ),
    ]
