# Generated by Django 4.2.3 on 2023-09-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_test', '0008_alter_user_schema_new_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_schema',
            name='new_1',
            field=models.TimeField(),
        ),
    ]
